server:
  port: 9090
spring:
  application:
    name: Friend Finder
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr

  jackson:
    serialization:

      write-dates-as-timestamps: false

    date-format: yyyy-MM-dd'T'HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

  messages:
    basename: i18n/messages

token:
  secret: 13396@MrMn19961331996$!#ShNa741118
  time: 24h


